name: super_widgets
description: A new Flutter package project.
version: 0.0.1
homepage: ''

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_extensions: ^2.2.2
  time: ^2.1.3
  intl: ^0.18.1
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  datetime_picker_formfield: ^2.0.1
  dotted_line: ^3.2.2
  dropdown_search: ^5.0.6
  file_picker_cross: ^4.6.0
  image_picker: ^1.0.0
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
#  flutter_svg_provider: ^1.0.3
  jovial_svg: ^1.1.15
  shape_of_view_null_safe: ^2.0.0
  curved_progress_bar: ^1.0.2
  progress_indicator: ^0.2.2
  url_launcher: ^6.1.11
  dotted_border: ^2.0.0+3
  draggable_scrollbar: ^0.1.0
  flutter_custom_clippers: ^2.1.0
  flutter_hooks: ^0.18.6
  simple_animations: ^5.0.2
  string_validator: ^1.0.0
  logger: ^1.4.0
  ready_extensions: ^1.3.0
  list_ext: ^1.0.6
  flutter_smart_dialog: ^4.9.3+1
  get: ^4.6.5
  get_storage: ^2.1.1
  responsive_framework: ^0.2.0
  flex_color_scheme: ^7.1.2
  date_field: ^3.0.5

#  Security
  uuid: ^3.0.7
  platform_device_id: ^1.0.1
  device_info_plus: ^9.0.2
  crypt: ^4.3.0
  root: ^2.0.4

  country_picker: ^2.0.20
  country_calling_code_picker: ^2.0.1
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  flutter_sim_country_code: ^0.1.2
  internet_file: ^1.2.0

  paged_vertical_calendar: ^1.1.6

  flutter_animate: ^4.2.0
  date_only_field: ^0.0.13
  package_info_plus: ^4.0.2

dependency_overrides:
  win32: ^2.4.1
  http: ^1.1.0
  ffi: ^2.0.2
  intl: ^0.18.1
  device_info_plus: ^9.0.2
  permission_handler: ^10.4.1
  flutter_svg: ^2.0.7
#  flutter_svg: ^1.0.5
  package_info_plus: ^4.0.2
  file_selector_linux: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2


flutter:
  assets:
    - assets/back_icon.svg
