name: super_widgets
description: A new Flutter package project.
version: 0.0.1
homepage: ''

environment:
  sdk: '>=2.19.0-244.0.dev <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_extensions: ^2.2.0
  time: ^2.1.3
  intl: ^0.18.0
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0
  datetime_picker_formfield: ^2.0.1
  dotted_line: ^3.1.0
  dropdown_search: ^5.0.6
  file_picker_cross: ^4.6.0
  image_picker: ^0.8.7
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  flutter_svg: ^1.0.1
  flutter_svg_provider: ^1.0.3
  jovial_svg: ^1.1.12
  shape_of_view_null_safe: ^2.0.0
  curved_progress_bar: ^1.0.2
  progress_indicator: ^0.2.2
  url_launcher: ^6.1.10
  dotted_border: ^2.0.0+3
  draggable_scrollbar: ^0.1.0
  flutter_custom_clippers: ^2.1.0
  flutter_hooks: ^0.18.6
  simple_animations: ^5.0.0+3
  string_validator: ^1.0.0
  logger: ^1.3.0
  ready_extensions: ^1.2.0
  list_ext: ^1.0.6
  flutter_smart_dialog: ^4.9.0+4
  get: ^4.6.5
  get_storage: ^2.1.1
  responsive_framework: ^0.2.0
  flex_color_scheme: ^7.0.0-dev.3

#  Security
  uuid: ^3.0.7
  platform_device_id: ^1.0.1
  device_info_plus: ^8.1.0
  crypt: ^4.2.1
  root: ^2.0.4

  country_calling_code_picker: ^2.0.1
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  flutter_sim_country_code: ^0.1.2
  internet_file: ^1.2.0

  paged_vertical_calendar: ^1.1.5

  flutter_animate: ^4.1.0
  date_only_field: ^0.0.13

dependency_overrides:
  ffi: ^2.0.1
  intl: ^0.18.0
  device_info_plus: ^8.1.0
  permission_handler: ^10.2.0
#  flutter_svg: ^2.0.4
  flutter_svg: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  assets:
    - assets/back_icon.svg
